[package]
name = "dyno"
version = "0.1.0"
authors = ["Hector Peeters <hector.peeters@gmail.com>"]
edition = "2018"

[dependencies]
logos = "0.11.4"
libc = "0.2.81"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm11-0"] }
